from setuptools import setup

setup(
    name="rl-interpretation-toolbox",
    version="0.0.2",
    author="pengzhenghao",
    author_email="pengzh@ie.cuhk.edu.hk",
    packages=[
        'toolbox',
        'toolbox.automation',
        'toolbox.process_data',
        'toolbox.train'
    ],
    install_requires=[
        "lz4",
        "Markdown",
        "matplotlib",
        "opencv-python",
        "pytest==4.3.1",
        "tensorflow-probability",
        "yapf==0.27",
        "numpy==1.16.0",
        "gym==0.17.1",
        "gym[mujoco]",
        "gym[box2d]",
        "gym[atari]",
        "gym-minigrid",
        "pandas",
        "yattag",
        "box2d-py==2.3.8",
        "sklearn",
        "seaborn",
        "distro",
        "gputil",
        "ray==0.8.4",
        "ray[tune]==0.8.4",
        "ray[rllib]==0.8.4",
        "ray[dashboard]==0.8.4",
        "ray[debug]==0.8.4",
        "dm-tree",
        "pybullet"
    ]
)
